### ISSUE TITLE
All metadata.json have the same properties

### ISSUE THREAD

**Issue by welli7ngton** [nycolasdiaas/zarea-de-risco#10]
Yesterday, while I was working on this PR (#8), I noticed that one operation was not working properly because my application was always returning the same JSON data. I had implemented an endpoint to retrieve data for a specific day, so the metadata.json file should only contain messages from that particular day. However, this is not what is happening—each metadata.json file contains the same data, including messages from all days. For the functionality to work properly, each JSON file should only include information relevant to its specific day.

You can reproduce the error by running the application locally and comparing the result from both endpoints:
- http://localhost:5000/get_all_metadata
- http://localhost:5000/get_metadata_from_date/<<string:date>>

**Comment by nycolasdiaas** [comment]
I noticed that as well, and I will take care of it.
@welli7ngton
